name: GitHub Actions and Terraform
on: [push]
jobs:
  deploy:

    runs-on: ubuntu-latest
    steps:
      - name: Install Terraform
        run: |
          cd /usr/bin
          curl -s -qL -o terraform.zip https://releases.hashicorp.com/terraform/1.2.2/terraform_1.2.2_linux_amd64.zip
          unzip -o terraform.zip
         
